//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerbatTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Container
    {
        public int ContainerId { get; set; }
        [Required(ErrorMessage = "Container Number is required")]
        public string ContainerNumber { get; set; }
        [Required(ErrorMessage = "Shipment Date is required")]
        public DateTime ShipmentDate { get; set; }
        [Required(ErrorMessage = "Origin Port is required")]
        public string OriginPort { get; set; }
        [Required(ErrorMessage = "Destination Port is required")]
        public string DestinationPort { get; set; }
        public string Status { get; set; }
        public string FilePath { get; set; }
    }
}
